---
title: "Michelle Mao, MD Resume"
author: "Michelle Mao"
date: "7/10/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About Me

##### I am a physician with a passion for education, data, and art. After attending TAMS from 2015 to 2017, I graduated from the University of Texas at Austin in 2020 with a BS in Human Biology and a minor in Spanish. I earned my MD from UT Southwestern Medical Center in 2024, and then completed one year of neurology residency at the University of Maryland before pivoting to a nonclinical career. This website serves as a portfolio for my projects related to my many interests. Outside of work, I enjoy making art, spending time outdoors, and exploring new places with friends.



### Contact Info

##### Email: <michellem1078@yahoo.com>
##### [Linkedin](linkedin.com/in/michelle-mao-m78)



### Education

##### Doctor of Medicine - UT Southwestern Medical School
###### 2020-2024

##### B.S. Human Biology | Spanish minor - University of Texas at Austin
###### 2017-2020

##### University of North Texas (Texas Academy of Math and Science)
###### 2015-2017



### Post-Graduate Training

##### Neurology Residency - University of Maryland
###### 2024-2025



### Work Experience

##### Resident Physician - University of Maryland Medical Center
###### Jun 2024 - Jul 2025
###### Cared for patients with complex acute and chronic medical conditions in several different contexts including inpatient wards, clinic, consults, and ICU

##### Medical Student Research Fellow - UT Southwestern Department of Physical Medicine and Rehabilitation / Department of Orthopedic Surgery 
###### May - Aug 2021
###### Collaboratively designed, recruited for, and executed a project studying the effect of sex-specific endocrine state on the joint inflammatory response to mechanical loading, resulting in a publication in Cartilage and an abstract for the 60th Annual Medical Student Research Forum

##### Teaching Assistant - University of Texas Biochemistry Department
###### Jan 2019 - May 2020
###### Assisted with lectures, lesson planning, and grading for BCH 369; tutored students during individual office hours; led group review sessions and moderated exams



### Publications

###### Mao M, Doyle A. Coxsackie B virus myositis in a healthy young man with mumps co-infection. IDCases. 2023 Jan 17;31:e01691. doi: 10.1016/j.idcr.2023.e01691. PMID: 36704025; PMCID: PMC9871301.

###### Hutcherson C, Mao M, Thakur B, Dhaher Y. Low-grade inflammatory mediators and metalloproteinases yield synchronous and delayed responses to mechanical joint loading. Cartilage. 2024 Dec;15(4):417-27.

###### George D, Li L, Jiang Y, Lowell D, Mao M, Hassan S, Ding J, Cui J, Zhang H, Philipose U, Lin Y. Localized surface plasmon polariton resonance in holographically structured Al-doped ZnO. Journal of Applied Physics. 2016 Jul 28;120(4):043109

##### Other - Magazine Publications
###### Doctor’s Daydream. 2021. Colored pencil. Scope UT Southwestern’s Art & Humanities Journal, Vol XI, 2021, p. 18. https://www.utsouthwestern.edu/life-at/scope/20



### Leadership and Activities

##### Co-Founder – Patient Education Initiative
###### Jan 2023 - present
###### Founded an initiative to improve health literacy by redesigning patient handouts to be more accessible

##### Committee Chair – Gold Humanism Honor Society
###### Mar 2023 - May 2024
###### Led a campaign to highlight the lives of Parkland Hospital patients via projects for sharing their stories; worked with other committees to promote wellness, ethics, and humanism at UT Southwestern

##### Committee Chair – United to Serve Community Health Fair
###### Sep 2020 - May 2024
###### Led the task force for creating the graphic design surrounding the annual Carnaval de Salud community health fair; hand-crafted virtual and physical design elements and designed the official t-shirt for the 2022 and 2024 fairs

##### Art Activities Coordinator - Therapeutic Arts Relieving Adverse Childhood Experiences (TRACE)
###### Jun 2021 – Jan 2022
###### Worked with art therapists to build an art activity curriculum, design activities, and coordinate supplies for TRACE, a medical student volunteering program that worked with children at the Dallas Juvenile Detention Center on therapeutic art projects informed by adverse childhood experiences

##### Co-Founder, Volunteering Coordinator – Longitudinal Geriatric Medicine Elective
###### Nov 2020 - Dec 2021
###### Built the outpatient volunteering curriculum for a medical school elective on aging and geriatric medicine and served as a student liaison leading the elective with faculty



### Awards and Honors

##### Gold Humanism Honor Society Member (2023)
##### UTSW Medical Student Summer Research Fellow (2021)
##### UT College of Natural Sciences Distinction in Service and Leadership (2019-2020)
##### UT Honors – College Scholar	(2019)



### Skills

##### Programming languages
###### R 
###### Python
##### Languages
###### English - native
###### Chinese (Mandarin) - read, write, and speak with fluency
###### Spanish - read, write, and speak with fluency
##### Electronic health records
###### Epic
###### CPRS


